// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqggvkkvxvthlvkciaui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxZ2d2a2t2eHZ0aGx2a2NpYXVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMDMxNzgsImV4cCI6MjA2Njc3OTE3OH0.33EA9QjPiUjGQVCY6U0W1dnSk1tIoIEhGeqWLmPKKjk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);